source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EVTopTabBar_Example', :exclusive => true do
  pod 'EVTopTabBar', :path => '../'
end

target 'EVTopTabBar_Tests', :exclusive => true do
  pod 'EVTopTabBar', :path => '../'

  
end
