source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EVTopTabBar_Example' do
  pod 'EVTopTabBar', :path => '../'
end

target 'EVTopTabBar_Tests' do
  pod 'EVTopTabBar', :path => '../'

  
end
