source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EVTopTabBar_Example' do
  platform :ios, '9.3'
  pod 'EVTopTabBar', :path => '../'
end

target 'EVTopTabBar_Tests' do
  platform :ios, '9.3'
  pod 'EVTopTabBar', :path => '../' 
end
